### ISSUE TITLE
create program+badge / print

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2024#82]

**Comment by garrying** [comment]
Front:
![Image](https://github.com/user-attachments/assets/7db11e0c-13cb-4a9c-ac7a-8f4afc54cdb4)

Back:
![Image](https://github.com/user-attachments/assets/22b97939-3c37-438a-9330-528127f25781)

**Comment by dcwalk** [comment]
- confirm lan urls
- add address for program on lan
- add any other addresses for activities
  - whiteboard?
  - files (ftp?)

**Comment by dcwalk** [comment]
confirmed:
ournetworks.local
archives.local
